#NGSgenotyp V2.0.0
#number of parallels job by defaut

# Command line options are in config now
# AppPath: "/netscratch/dep_mercier/grp_novikova/software/ngsg/"

# Most important ones are here:
MaxParallelsJobs: 20
outfolder: ngsg
readsinfo: ../reads_list_reduced
fastaref: ../Ahalleri_SRK_Database.fa

# Here come other former CLI arguments:

# genotyp CLI
kmerfilter: True
kmerSize: 20
mismatchthrld: 0
pdfreports: False
statsonly: False
sharedreads: False
statsmismatchthrld: False
keepindel: False
readsMappedThrld: 10
alignmentMode: end-to-end
alignmentSensitivity: very-sensitive
refexclude: null
outnbsheetperxls: 15

# haploasm CLI
paired: False
includeParalogsyass: False
includeParalogstree: False
threaded: 8
indivlist:
contigminlen: 500
contigmaxlen:
genotypfolder: .
asmsuffix: asmv1
assembler: spades

#allowed_fasta_params: ['Paralog', 'specie', 'grpRef']

#Parameters to define genotyp threshold value
genotyp_def_ErrorRate: 0.05
genotyp_alleleProb_THRLD: 0.00001

#parameters for genotyp score calculation
#logNormal parameters mean (μ) and standard deviation (σ)
mu : 0.01992734
sigma : 0.01024804

#exponential distribution
#here because of distribution, lbda = 1/(1-"expected value") 108.212560
lbda : 108.212560

#error rate limit for SharedReads xls files
sharedReads_errorRatelim: 0.1

#Log file
log_folder : logs

#Pipeline folders V2
OutFolders:
  bwt_dirResult: BWT_Results
  out_splited: FQ_splited
  out_filtered: FQ_filtered
  main_results_dir: Results
  reference_DB_fld: Refs
  configs_fld: configs
  bwt_IndexdirResult: Refs/BWT_RefIndexes
  single_fasta_ref_fld: Refs/Single_Fastas
  assembly_out: Assembly
  
#config files name
index_cfg: bwt2_index.yaml
KRF_yamlFile: kmerRefFilter_resume.yaml
readsconfig: complete_readsConfig.yaml
assembly_config: asm_config.yaml

############# genotyp configs

#reads filenames
splited_reads: splited_reads.yaml

#results files
xls_shared_reads: shared_reads.xls
samtools_stats: samtools_stats.yaml
SortKey: 'gscore'
sortOrderReverse: True


#Bowtie results
bwt_IndexdirResult: 'BWT_RefIndexes'
bwt_build_out: 'bwt-build_out.txt'
bwt_dirResult: 'BWT_Results'

#Warnings messages list
Warn_refLen : "Ref. Length"


############# haploasm configs

YASSstep:
  yass_params: '-E 1e-10 -m 10 -s 6 '
  Thresholds:
    #parameters: 'percent_identity', 'alignment_length', 'mismatches', 'gap_openings', 'e-value', 'bit_score', 'ref_length', 'coverage', 'ident_cov', 'contig_depth', 'strand'
    
    percent_identity: '>=80.0'
    coverage: '>=0.5'
    
ASMtools:
  spades:
    # cmdline: "-t {thrds} --careful -k {kmerS} -o . {fastq} > {logf}"
    cmdline: "-t {thrds} --careful -k {kmerS} -o {outf} {fastq} > {logf}"
    options:
      fwd: "--pe1-1 "
      rev: "--pe1-2 "
      single: "--s1 "
    out_contigs: contigs.fasta
    kmers: "21,41,81"
    fastq_sep: " "
    path: spades.py
    regex_cov: '(?<=cov_)\d+\.\d+'
    regex_contig_nbr: '(?<=NODE_)\d+'
  minia:
    # cmdline: "-nb-cores {thrds} -in {fastq} -out asm_minia > {logf}"
    cmdline: "-nb-cores {thrds} -in {fastq} -out {outf}/asm_minia > {logf}"
    options:
      fwd: ""
      rev: ""
      single: ""
    out_contigs: asm_minia.contigs.fa
    kmers:
    fastq_sep: ","
    path: minia
    regex_cov: '(?<=km:f:)\d+\.\d+'
    regex_contig_nbr: '\d+'
#Configuration file for NGSgenotyp tools

# Tools configuration (to be sanitized)
#Fastq filtering
kmerRefFilter:
  uselocal: True
  bin_folder: kmerRefFilter-1.5/
