channels:
  - bioconda
  - conda-forge
dependencies:
  - python>=3.9.6
  - snakemake
  - parallel
  - matplotlib
  - biopython
  - bowtie2
  - samtools
  - muscle=3.8
  - phyml
  - spades
  - csvtk
  # - quast
  # - cap3
  # - minia
  - scipy
  - numpy
  - pysam
  - ete3
  - pyyaml
  - xlrd
  - xlwt
  - psutil
